name: gds
on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky26a
        with:
          pdk: sky130A

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky26a

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttsky26a
      - name: Check results exist
        id: check
        if: always()
        run: |
          [ -f test/results.xml ] && echo "exists=true" >> $GITHUB_OUTPUT || echo "exists=false" >> $GITHUB_OUTPUT
      - name: Test summary
        if: always() && steps.check.outputs.exists == 'true'
        uses: test-summary/action@v2.3
        with:
          paths: test/results.xml

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttsky26a
